version: "2"

networks:
  main:

services:
  lein:
    image: trade:LATEST
    build:
      context: .
    volumes:
      - ".:/usr/src/app"
      - "./.m2:/root/.m2"
    entrypoint: ["lein"]
    command: ["run"]
    working_dir: "/usr/src/app"
    networks:
      main:
        aliases:
          - trader
  prometheus:
    image: prom/prometheus:v2.9.2
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "./prometheus-data:/prometheus:rw"
    ports:
      - "9090:9090"
    links:
      - "lein:trader"
    networks:
      - main
